# Generated by Django 4.2.7 on 2023-12-28 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idmetamaxk', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ThuCung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pet', models.CharField(max_length=200)),
                ('day_of_birth', models.DateTimeField()),
                ('sex', models.BooleanField(default=0)),
                ('animal_type', models.CharField(max_length=200)),
                ('pet_image', models.ImageField(default='', upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
