# Generated by Django 4.2.7 on 2023-12-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thucung',
            name='father',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='thucung',
            name='hop_dong',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='thucung',
            name='mother',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='thucung',
            name='animal_type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='thucung',
            name='name_pet',
            field=models.CharField(default='', max_length=200),
        ),
    ]
